Fix a couple of funny uses of \si.
geodynamics/aspect pull request #3832
Opened 2020-08-31 19:54 UTC by bangerth

Mentioned in https://github.com/geodynamics/aspect/pull/3798#discussion_r479693148

2020-09-01 10:19 UTC, bobmyhill requested changes

2020-09-01 10:19 UTC, bobmyhill commented on doc/manual/manual.tex
> +  \si{K/kg/K^2 ($-\Delta S \frac{\partial X}{\partial T}) and
```suggestion
  \si{J/kg/K^2 ($-\Delta S \frac{\partial X}{\partial T}) and
```

2020-09-01 10:19 UTC, bobmyhill commented on doc/manual/manual.tex
> +  For the earth mantle, a value of $1250
```suggestion
  For the Earth's mantle, a value of $1250
```

2020-09-01 16:01 UTC, bobmyhill commented on doc/manual/manual.tex
> +  \si{m^3/kg/K} ($\Delta S \frac{\partial X}{\partial p}).
```suggestion
  \si{m^3/kg/K} ($\Delta S \frac{\partial X}{\partial p}$).
```

2020-09-03 18:45 UTC, bangerth commented on doc/manual/manual.tex
> +  \si{K/kg/K^2 ($-\Delta S \frac{\partial X}{\partial T}) and
Oh, 3 mistakes in one line...

2020-09-03 18:46 UTC, bangerth commented
Thanks, @bobmyhill . So fixed!

2020-09-03 19:04 UTC, bobmyhill commented
> Thanks, @bobmyhill . So fixed!

Great!

2020-09-03 19:18 UTC, gassmoeller approved these changes
Looks good to me. @bobmyhill do you think this is ready to merge?

2020-09-03 21:07 UTC, bobmyhill commented
@gassmoeller, yes, this looks good to me!

2020-09-03 21:07 UTC, bobmyhill approved these changes

2020-09-14 16:03 UTC, merged