[WIP] Splitting ViscoPlastic into rheology module
geodynamics/aspect pull request #3908
Opened 2020-11-29 16:38 UTC by bobmyhill

* [x] I have followed the [instructions for indenting my code](../blob/master/CONTRIBUTING.md#making-aspect-better).
* [x] I have tested my new feature locally to ensure it is correct.

2020-12-04 14:32 UTC, bobmyhill commented
/rebuild

2020-12-04 21:46 UTC, naliboff requested changes
👏 👏 👏 👏  - A round of applause, this is fantastic! I have one comment regarding documentation, but that is it for now. 

I think one of the other developers should have a look as well before merging, but in the end this is just moving code and I'm having a hard time anticipating any issues that the tester would not catch. @anne-glerum @MFraters @jdannberg @gassmoeller - Does one of you have time to take a look over the next few days?

2020-12-04 21:46 UTC, naliboff commented on include/aspect/material_model/visco_plastic.h
> +         * Object for computing viscosities.
I think the documentation for this object should be expanded quite a bit. While one the functions does compute the viscosity, this object also points to functions for additional material model outputs, the Newton derivatives, etc. Perhaps a more accurate single sentence description would be 'Object for rheology operations'. However, my preference would be to have an expanded description.

2020-12-04 22:03 UTC, bobmyhill commented
Thanks for the quick review! I've extended the documentation as requested.

2020-12-04 22:35 UTC, naliboff approved these changes
@bobmyhill - Thanks, the new documentation looks great! Good to go from my end, but lets wait for another review.

2020-12-09 17:05 UTC, anne-glerum approved these changes
Thanks @bobmyhill ! I've only got textual/formatting comments, and most of those are about things not introduced by this PR. Not sure whether those should be addressed in a separate PR or can just be added to this PR. What do you think @naliboff ?

2020-12-09 17:52 UTC, naliboff commented
@anne-glerum - Thanks for the second review! If @bobmyhill does not mind documenting the parameters mentioned above, maybe easiest to do it in this PR? Bob - if you are ok with this, I'll add some suggestions for the missing parameter documentation to speed things up.

2020-12-09 18:00 UTC, bobmyhill commented
Thanks @anne-glerum! The commenting is much more uniform now :) 
@naliboff, I've made the changes suggested. Is anything else needed, or is this ready to go now (once the tester confirms that it is still happy)?

2020-12-09 18:29 UTC, naliboff reviewed
@bobmyhill - Two more minor comments on my end (feel free to ignore them), but after that ready to merge. Thank you again for this major improvement!

2020-12-09 18:29 UTC, naliboff commented on include/aspect/material_model/rheology/visco_plastic.h
> +           * Reference strain rate for the first time step.
Suggestion: `Reference strain rate for the first non-linear iteration in the first time step`

2020-12-09 18:29 UTC, naliboff commented on include/aspect/material_model/rheology/visco_plastic.h
> +           * Minimum strain rate used to stabilize the strain dependent rheology.
Should this be` strain rate dependent rheology`?

2020-12-09 18:36 UTC, bobmyhill commented
Ok, great! I've made those changes, so this is now ready to go :)

2020-12-09 19:49 UTC, merged