Add an explanatory sentence to the 'compositing' material model.
geodynamics/aspect pull request #4044
Opened 2021-05-25 21:26 UTC by bangerth

Following up on a conversation I had with @paddyball today.

/rebuild

2021-05-28 15:56 UTC, anne-glerum requested changes

2021-05-28 15:56 UTC, anne-glerum commented on source/material_model/compositing.cc
> +                                   "use the melting parameterization of the `melt simple' model (which has "
In the sentence above, two ticks are used for the name of the compositing material model (``compositing''). I don't know whether we use one or two ticks, but I guess it should be the same everywhere.

2021-05-28 15:56 UTC, anne-glerum commented on source/material_model/compositing.cc
> +                                   "`diffusion dislocation' model."
same here

2021-06-01 16:28 UTC, bangerth commented
Good points, @anne-glerum . Fixed!

2021-06-03 18:57 UTC, anne-glerum approved these changes

2021-06-03 18:57 UTC, anne-glerum commented
Looks good to me, can I just merge it now?

2021-06-03 20:14 UTC, bangerth commented
Yes, please :-)

2021-06-04 11:06 UTC, merged