Avoid string comparisons in spherical constant boundary temperature plugin
geodynamics/aspect pull request #4089
Opened 2021-06-25 18:24 UTC by gassmoeller

The 'spherical constant' boundary temperature and composition plugins currently does a lot of string comparisons when returning the boundary values, so many that they show up when profiling instantaneous models. The gain for the overall model is not huge, but it is a simple change that makes the plugin more similar to the way the box plugins are written already.

I also removed the `minimal_composition` and `maximal_composition` functions from the boundary composition plugin. I think they were copy-pasted from the temperature plugin, because such functions are not defined in the composition interface, and they are nowhere used.

@jdannberg I know you had looked at these plugins before, can you take a look at this?

2021-06-25 23:53 UTC, tjhei approved these changes

2021-06-25 23:53 UTC, tjhei commented on source/boundary_composition/spherical_constant.cc
> +          if (boundary_names_map.find("bottom") != boundary_names_map.end())
should we bail out here is there is not top/bottom instead?

2021-06-26 21:45 UTC, tjhei commented
can this wait until after 2.3?

2021-06-27 15:59 UTC, gassmoeller commented
This does not need to go into 2.3. I improved the documentation and error checks and fixed the tests. There is some  awkward behavior in that several places expect this boundary plugin to work for both boundaries even for a full sphere that only has a single boundary. I restored the current behavior, but it looks a bit weird.

2021-06-29 05:07 UTC, jdannberg reviewed
Thank you for fixing my old code from 8 years ago! This looks good to me, except for my one comment.

2021-07-01 19:43 UTC, bangerth requested changes
I have to admit that I don't like storing the inner/outer values in a `std::vector`. The previous scheme was clear by using two variables for it. If you'd like to avoid this, maybe use a `std::map`, but with the `std::vector`, there is an implicit assumption that inner and outer boundaries are associated with `boundary_id` zero and one, and that seems questionable to me and not scalable.

2021-07-02 02:37 UTC, jdannberg commented on include/aspect/boundary_composition/spherical_constant.h
> -        double minimal_composition (const std::set<types::boundary_id> &fixed_boundary_ids) const;
I am not sure they were ever there in the interface (and if they were, they weren't used for anything). I wrote this code when I came to visit you in Texas the very first time, and I think I simply copied everything from the same plugin for the boundary temperature.

2021-07-02 02:40 UTC, jdannberg commented on source/boundary_composition/spherical_constant.cc
> +      (void) compositional_field;
The change is fine, I just want a changelog entry in case someone was using this and needs to figure out why their models aren't working any more.

2021-07-02 16:37 UTC, bangerth commented on include/aspect/boundary_composition/spherical_constant.h
> -        double minimal_composition (const std::set<types::boundary_id> &fixed_boundary_ids) const;
Ha :-)

2021-07-21 12:40 UTC, bangerth commented
Ping?

2021-07-21 15:38 UTC, gassmoeller commented
This will have to wait until I am back from vacation in 2 weeks. Making things consistent with our other plugins will require more or less a rewrite of the whole plugin.

2021-07-21 16:51 UTC, bangerth commented
Enjoy your vacation, it's well deserved after the hackathon!

2022-05-22 01:24 UTC, bangerth commented
@gassmoeller Want to revive this one as well?

2023-07-15 19:02 UTC, bangerth commented
@gassmoeller Still interested in this? Or should we close the issue?

2023-08-02 19:34 UTC, gassmoeller commented
Thanks for reminding me (repeatedly over years :-)). Yes, I would still like to finish this PR. I pushed a new version that should address most comments by staying closer to the original implementation and also preserved legacy behavior (to assign the same value to all compositional fields if only one value is prescribed). This now also adds the functionality to prescribe different values to different compositional fields. From my point this is ready for another review, I just need to wait to update the tester results.

2023-10-07 22:26 UTC, jdannberg reviewed
This looks reasonable to me, but you do not have a test of your new features (especially since you changed existing tests to now use a different model instead).

2023-10-07 22:26 UTC, jdannberg commented on source/geometry_model/interface.cc
>              errno = 0;
Would it make sense to use `Utilities::string_to_int` here since that now hopefully should have the error checking?

2023-10-07 22:54 UTC, gassmoeller commented
Thanks for the review. I accidentally force pushed an older version of this branch, and I dont have access to the new version right now. I will address this next week.

2023-10-09 17:44 UTC, gassmoeller commented
@jdannberg Thanks for  the review. I added a test.

@bangerth: You requested changes and we cannot merge this PR until you accept the changes. Can you take a look if this is good enough now?

2023-10-09 19:19 UTC, jdannberg approved these changes
Thank you for making the changes!

2023-10-10 03:27 UTC, bangerth approved these changes

2023-10-10 03:28 UTC, merged