Remove unused PETSC option
geodynamics/aspect pull request #4112
Opened 2021-07-01 18:00 UTC by KiralyAgi

This removes an old PETSC option

2021-07-01 19:06 UTC, bangerth requested changes
This looks ok, but you have a lot of merge commits in your branch. Do you know how to get rid of these (and, why they are there in the first place)?

2021-07-01 20:02 UTC, bangerth commented
Related to #3338.

2021-07-02 08:35 UTC, KiralyAgi commented
Hi Wolfgang,

I agree, it is strange that there are so many commits. As far as I see, they all originated from the times I updated ASPECT from the upstream. I usually do git pull upstream and then git push origin master. When I pull from upstream it always creates a commit for merging. But I don't know why is this visible on this branch. Is there a way to get the updates without having a commit for each time?

2021-07-02 09:57 UTC, KiralyAgi commented
Okay, solved it! I followed the advice from here: https://stackoverflow.com/questions/33502205/how-to-delete-merge-commits

2021-07-02 16:33 UTC, tjhei commented on source/simulator/core.cc
> -    sp.compress();
Keep this line, please.

2021-07-06 10:01 UTC, KiralyAgi commented
I couldn't figure out how to change back 1 deleted line, so I did it all over again, and now it should be updated with the correct lines deleted/not-deleted

2021-07-06 14:39 UTC, tjhei approved these changes
Looks good!

2021-07-06 14:54 UTC, merged