Add a note about compositional fields to the manual.
geodynamics/aspect pull request #4343
Opened 2021-09-07 21:36 UTC by bangerth

2021-09-07 21:48 UTC, bobmyhill requested changes

2021-09-07 21:48 UTC, bobmyhill commented on doc/manual/manual.tex
> +  historic: These fiels were meant to track chemical compositions, but
```suggestion
  historic: These fields were meant to track chemical compositions, but
```

2021-09-07 21:48 UTC, bobmyhill commented on doc/manual/manual.tex
> +  as simply a \textit{technical term} in which the two words appear
```suggestion
  as a \textit{technical term} in which the two words appear
```

2021-09-07 21:48 UTC, bobmyhill commented on doc/manual/manual.tex
> +  cases track nothing at all and just be static fields that do not
```suggestion
  cases track nothing at all and just be static fields that
```

2021-09-07 21:48 UTC, bobmyhill commented on doc/manual/manual.tex
> +  change over time and whose values may simply indicate where some
```suggestion
simply indicate where some
```
Remove tautology

2021-09-17 20:54 UTC, bangerth commented
Thanks, @bobmyhill -- so fixed!

2021-09-17 23:35 UTC, bobmyhill approved these changes

2021-09-17 23:35 UTC, merged