add noninitial plastic strain property
geodynamics/aspect pull request #4545
Opened 2022-04-15 22:05 UTC by naliboff

This pull request enables the visco plastic strain invariant particle property to track noninitial plastic strain, and also (hopefully) improves the code structure and documentation. I tested this locally with a new test case, but we will see what happens with the existing tests.

* [X] I have followed the [instructions for indenting my code](../blob/main/CONTRIBUTING.md#making-aspect-better).
* [X] I have tested my new feature locally to ensure it is correct.
* [ ] I have [created a testcase](http://www.math.clemson.edu/~heister/manual.pdf#sec%3Awriting_tests) for the new feature/benchmark in the [tests/](../blob/main/tests/) directory.
* [ ] I have added a changelog entry in the [doc/modules/changes](../blob/main/doc/modules/changes) directory that will inform other users of my change.

2022-04-18 18:09 UTC, naliboff commented
/rebuild

2022-04-19 08:14 UTC, anne-glerum requested changes
Thank you John, that's a lot clearer! Can you add a test that tracks the noninitial strain on particles?

2022-04-19 08:14 UTC, anne-glerum commented on source/particle/property/viscoplastic_strain_invariants.cc
>          if (this->introspection().compositional_name_exists("viscous_strain") && plastic_yielding == false)
Thank you for adding the list of assumptions above, it's much clearer! Could you please also add for each of the below conditions a comment that explains what situation we're in? I'll add some examples below. I think that will make it easier to change the code if we ever change the assumptions.

2022-04-19 08:14 UTC, anne-glerum commented on source/particle/property/viscoplastic_strain_invariants.cc
> +            if (n_components == 1)
`// Not yielding and only one field, which tracks the viscous strain`

2022-04-19 08:14 UTC, anne-glerum commented on source/particle/property/viscoplastic_strain_invariants.cc
> +            if (n_components == 2)
`// Not yielding, two fields, second is viscous strain.`

2022-04-19 08:14 UTC, anne-glerum commented on source/particle/property/viscoplastic_strain_invariants.cc
> +            if (n_components == 3)
`// Not yielding, three fields (plastic strain, viscous strain, nonintial plastic strain).`

2022-05-04 02:15 UTC, naliboff commented
@anne-glerum - Thanks for the review and I've hopefully addressed all of the comments. Good idea to add a description above each scenario, which will make this much easier to update later on. Please let me know if any additional changes are needed.

2022-05-04 20:08 UTC, anne-glerum requested changes
Thanks for adding the test! Could you please add a line about the noninitial_plastic_strain in the description of the particle property at the bottom of the cc file? Sorry I didn't see that before.

2022-05-04 20:08 UTC, anne-glerum commented on tests/visco_plastic_yield_noninitial-plastic-strain_particles.prm
> +# produce a incremental strain of 1e-5 per time step and material that is always yielding.
```suggestion
# produce an incremental strain of 1e-5 per time step and material that is always yielding.
```

2022-05-05 02:24 UTC, naliboff commented on tests/visco_plastic_yield_noninitial-plastic-strain_particles.prm
> +# Particles mapped to the Compositional fields used to track plastic, noninitial plastic, and viscous strain.
Yep, it took me a bit of looking to figure out this out as well!

2022-05-05 02:46 UTC, naliboff commented
@anne-glerum - Thanks for the additional review and suggestions! I've incorporated all of the suggestions and also simplified the logic in the viscous strain update section, per your recommendation. Assuming the tests still pass, let me know if you would like any additional changes.

2022-05-05 07:46 UTC, anne-glerum approved these changes
Great thank you!

2022-05-05 07:51 UTC, anne-glerum commented
Do you think this warrants a change log entry?

2022-05-05 19:48 UTC, naliboff commented
@anne-glerum - Good point, I added a change log entry.

2022-05-06 08:50 UTC, anne-glerum approved these changes

2022-05-06 08:51 UTC, merged

2022-05-06 08:51 UTC, anne-glerum commented
Thanks John!