Documentation: Running models
geodynamics/aspect pull request #4675
Opened 2022-05-19 19:32 UTC by ljhwang

Fixes a few formatting errors.
Still needs a correct reference for @cmillls1095 to fix :)

2022-05-20 02:17 UTC, bangerth requested changes

2022-05-20 02:17 UTC, bangerth commented on doc/sphinx/user/install/docker-container/running-models.md
> +Fix referenced link to Sectio 4.4 Debug or Optimized
```suggestion
Fix referenced link to Section 4.4 Debug or Optimized
```

2022-05-20 02:17 UTC, bangerth commented on doc/sphinx/user/install/docker-container/running-models.md
> +    a discussion of the different versions see {ref}4.4][], in
How do we want to deal with this going forward? We can't reasonably have numbers be the labels for sections.

2022-05-20 02:17 UTC, bangerth commented on doc/sphinx/user/install/docker-container/running-models.md
> +also more reliable workflow.
Is it not possible to have the footnote text right where the footnote symbol is? It is hard to maintain things if pieces of related text end up in different places in the document.

2022-05-23 22:21 UTC, ljhwang commented
Again this has picked up unresolved conflicts so I will close as most of them have been addressed.

2022-05-23 22:21 UTC, closed without merging