Add strain rate particle property
geodynamics/aspect pull request #4690
Opened 2022-05-19 21:17 UTC by KiralyAgi

I added a new plugin to particle/property/strainrate, to save the local strain rate on the particles.

2022-05-19 22:15 UTC, MFraters requested changes
A few small changes requested. Could you also indent the code and add a test?

2022-05-19 22:15 UTC, MFraters commented on include/aspect/particle/property/strainrate.h
> + Copyright (C) 2015 - 2021 by the authors of the ASPECT code.
Please update

2022-05-19 22:15 UTC, MFraters commented on include/aspect/particle/property/strainrate.h
> +       * A class that sets particle properties to the current velocity.
strain-rate instead of velocity?

2022-05-19 22:15 UTC, MFraters commented on source/particle/property/strainrate.cc
> +  Copyright (C) 2015 - 2021 by the authors of the ASPECT code.
please update

2022-05-19 22:15 UTC, MFraters commented on source/particle/property/strainrate.cc
> +        //std::cout<<"grad_u: "<<grad_u<<std::endl;
please remove this line.

2022-05-19 22:15 UTC, MFraters commented on source/particle/property/strainrate.cc
> +        //std::cout<<"strainrate: "<<strain_rate<<std::endl;
remove this line

2022-05-19 22:15 UTC, MFraters commented on source/particle/property/strainrate.cc
> +                                        "property is defined as the recent strainrate at "
strain rate is two words. I think we usually write `StrainRate` for the class, `strain_rate` for the file name  and `strain rate` for the string name. See https://github.com/geodynamics/aspect/blob/main/source/postprocess/visualization/strain_rate.cc for an example.

2022-05-20 03:45 UTC, KiralyAgi commented
I renamed the files to strain_rate, the class to StrainRate, and the string to strain rate. Added a test.

2022-05-20 15:04 UTC, gassmoeller commented
/rebuild

2022-05-21 15:36 UTC, MFraters approved these changes
One small comment, otherwise good to go.

2022-05-21 15:36 UTC, MFraters commented on include/aspect/particle/property/strain_rate.h
> +       * A class that sets particle properties to the current strain rate.
Please update this to strain rate from the previous time step

2022-05-27 20:21 UTC, gassmoeller commented
Apart from Menno's comment, you will also have to update the test results with the reference results. Let me know if you need help with it (also see here https://aspect-documentation.readthedocs.io/en/latest/user/extending/testing/writing-tests.html).

2022-06-20 20:07 UTC, gassmoeller commented
Thank you! Ready to go.

2022-06-20 20:07 UTC, merged