move composition velocity statistics from cookbook to main branch
geodynamics/aspect pull request #4932
Opened 2022-08-02 15:48 UTC by elodie-kendall

Pull Request Checklist. Please read and check each box with an X. Delete any part not applicable. Ask on the [forum](https://community.geodynamics.org/c/aspect) if you need help with any step.

After a discussion with Anne, I moved the postprocessor "composition velocity statistics" from the cookbook "kinematically_driven_subduction_2d" to the main branch as it's a useful feature for myself and some others. This way the user does not have to keep compiling the .so file etc.

### Before your first pull request:

* [ X] I have read the guidelines in our [CONTRIBUTING.md](../blob/main/CONTRIBUTING.md) document.

### For all pull requests:

* [X ] I have followed the [instructions for indenting my code](../blob/main/CONTRIBUTING.md#making-aspect-better).

### For new features/models or changes of existing features:

* [X ] I have tested my new feature locally to ensure it is correct.
* [ ] I have [created a testcase](http://www.math.clemson.edu/~heister/manual.pdf#sec%3Awriting_tests) for the new feature/benchmark in the [tests/](../blob/main/tests/) directory.
* [X ] I have added a changelog entry in the [doc/modules/changes](../blob/main/doc/modules/changes) directory that will inform other users of my change.

2022-08-03 11:53 UTC, anne-glerum reviewed
I haven't reviewed the changes, I just wanted to mention one thing.

2022-08-03 11:53 UTC, anne-glerum commented on CMakeLists.txt
> -
Please undo changes to this file, I don't think they are related to this PR.

2022-08-03 11:53 UTC, anne-glerum commented
/rebuild

2022-08-09 10:13 UTC, elodie-kendall commented
I'm not sure why this is failing and the changes-test-results-master.diff is empty. Could someone advise me please? Thanks!

2022-08-11 14:29 UTC, anne-glerum commented on doc/modules/changes/20220729_ekendall
> +Changed: Moved composition velocity statistics script from cookbook to main code. I also changed the parameter terminology from "slab" to the more general name "selected_field".
```suggestion
Changed: Moved composition velocity statistics postprocessor from cookbook to main code. 
Compatibility of the input parameter is broken by renaming "slab" to the more general "selected_field". 
```

2022-08-11 14:40 UTC, anne-glerum requested changes
Hi @elodie-kendall, I made some suggestions for the naming of the variables so that they better reflect what they are.

2022-08-11 14:40 UTC, anne-glerum commented on include/aspect/postprocess/composition_velocity_statistics.h
> +        std::vector<std::string> selected_field_compositions;
This name is a bit confusing. Several 'compositional fields' can make up an entity of which the rms velocity is to be computed. Maybe call it 'selected_fields' or 'selected_compositional_fields'?

2022-08-11 14:40 UTC, anne-glerum commented on source/postprocess/composition_velocity_statistics.cc
> +      // compute the RMS velocity for each compositional field and for the selected compositonal field
```suggestion
      // compute the RMS velocity for each compositional field and for the selected compositional fields combined
```

2022-08-11 14:40 UTC, anne-glerum commented on source/postprocess/composition_velocity_statistics.cc
> +      double velocity_square_integral_selected_field = 0., area_integral_selected_field = 0.;
```suggestion
      double velocity_square_integral_selected_fields = 0., area_integral_selected_fields = 0.;
```

2022-08-11 14:40 UTC, anne-glerum commented on source/postprocess/composition_velocity_statistics.cc
> +      double velocity_square_integral_selected_field = 0., area_integral_selected_field = 0.;
Please update the names everywhere.

2022-08-11 14:40 UTC, anne-glerum commented on source/postprocess/composition_velocity_statistics.cc
> +      const double vrms_selected_field = std::sqrt(velocity_square_integral_selected_field) / std::sqrt(area_integral_selected_field);
```suggestion
      const double vrms_selected_fields = std::sqrt(velocity_square_integral_selected_fields) / std::sqrt(area_integral_selected_fields);
```

2022-08-11 14:40 UTC, anne-glerum commented on source/postprocess/composition_velocity_statistics.cc
> +      // Also output the selected field vrms
```suggestion
      // Also output the selected fields' vrms
```

2022-08-11 14:40 UTC, anne-glerum commented on source/postprocess/composition_velocity_statistics.cc
> +      // Also output the selected field vrms
Please update below accordingly

2022-08-11 14:40 UTC, anne-glerum commented on source/postprocess/composition_velocity_statistics.cc
> +          prm.declare_entry("Names of selected compositional fields", "",
The text of this parameter needs to be updated as well, i.e. 'the subducting plate' should be changed.

2022-08-11 14:40 UTC, anne-glerum commented on source/postprocess/composition_velocity_statistics.cc
> +                                 "fields must be larger than zero "
```suggestion
                                 "fields for which the RMS velocity is to be summed must be larger than zero "
```

2022-08-12 08:22 UTC, elodie-kendall commented
Thanks, I've addressed your comments

2022-08-16 15:27 UTC, anne-glerum requested changes
Just 2 tiny comments. Now that this plugin is moved, we need a test that uses it as well. Can you provide one?

2022-08-16 15:27 UTC, anne-glerum commented on source/postprocess/composition_velocity_statistics.cc
> +      return std::pair<std::string, std::string>("RMS velocity for compositions and selected field:",
```suggestion
      return std::pair<std::string, std::string>("RMS velocity for compositions and combined selected fields:",
```

2022-08-16 15:27 UTC, anne-glerum commented on source/postprocess/composition_velocity_statistics.cc
> +                            "you want to compute the RMS velocity for.");
```suggestion
                            "you want to compute the combined RMS velocity for.");
```

2022-08-16 15:29 UTC, anne-glerum commented
Can someone else have a look at this as well?

2022-08-18 16:09 UTC, elodie-kendall commented
Thanks for your last comments. I addressed them and added a test. I'll patch it after a final review.

2022-08-19 12:53 UTC, tjhei approved these changes

2022-08-19 12:54 UTC, tjhei commented on tests/kinematically_driven_subduction_2d_case1.prm
> +# but with lower resolution. It models oceanic
```suggestion
# but with lower resolution. It models oceanic
```
Remove the space at the end of this line.

2022-09-07 13:05 UTC, anne-glerum requested changes

2022-09-07 13:05 UTC, anne-glerum commented on doc/modules/changes/20220729_ekendall
> +Added: A test which is a replica of the cookbook "kinematically_driven_subduction_2d_case1" but with lower resolution and shorter end time.
Please delete this line. Tests are added by default, so no need to report it.

2022-09-07 13:05 UTC, anne-glerum commented
Hi Elodie, can you please delete the lines I mention above and patch the test results? Then this is ready to go!

2022-09-09 13:38 UTC, anne-glerum approved these changes

2022-09-10 15:39 UTC, elodie-kendall commented
When I try to patch the test I get the error "Reversed (or previously applied) patch detected!  Assume -R? [n] n
" and if I press enter it says "Hunk #1 FAILED at 1.
Hunk #2 FAILED at 62.
2 out of 2 hunks FAILED"

2022-09-20 07:04 UTC, anne-glerum commented
https://jenkins.tjhei.info/job/aspect/job/PR-4932/14/artifact/changes-test-results.diff

2022-09-20 10:25 UTC, anne-glerum commented
Hi @elodie-kendall I'm sorry but this PR now includes changes to rheology and material model files. Can you remove those?

2022-09-20 13:11 UTC, anne-glerum commented
Great, thanks for removing those files! There's one more empty line to remove with the diff:
https://jenkins.tjhei.info/job/aspect/job/PR-4932/16/artifact/changes-test-results.diff

2022-09-20 18:59 UTC, anne-glerum commented
@tjhei the now failing test is unrelated (FPE), can this be ignored?

2022-09-21 16:57 UTC, gassmoeller reviewed
Just a small comment. Seems good otherwise.

2022-09-21 16:57 UTC, gassmoeller commented on changes-test-results.diff
> +diff --git a/tests/kinematically_driven_subduction_2d_case1/screen-output b/tests/kinematically_driven_subduction_2d_case1/screen-output
This file should not be added to the git history. Can you remove it by running `git rm ...` and then amend the commit (`git commit --amend`) and force push to this PR?

2022-09-26 17:14 UTC, gassmoeller approved these changes
Thanks!

2022-09-26 17:14 UTC, merged

2022-09-28 12:03 UTC, elodie-kendall commented
Thanks @gassmoeller and @anne-glerum