Standardize 2D->2d and 3D->3d.
geodynamics/aspect pull request #5050
Opened 2023-02-04 17:19 UTC by bangerth

Seen while looking at #5041. We have a funny mix between 2d/3d and 2D/3D:
```
projects/aspect> egrep -r '\".*[23]d' include source/ | wc -l
123
projects/aspect> egrep -r '\".*[23]D' include source/ | wc -l 
82
```
So the lower-case `d` wins statistically speaking, and this patch fixes this uniformly in strings, almost all of which appear to be in the descriptions of parameters and models. Let's see whether this compiles and tests alright.

/rebuild

2023-02-04 18:13 UTC, tjhei requested changes

2023-02-04 18:13 UTC, tjhei commented on source/structured_data.cc
> +        prm.declare_entry("Slice dataset in 2d plane", "false",
This will break things.

2023-02-04 18:13 UTC, tjhei commented on source/structured_data.cc
> +        slice_data = prm.get_bool ("Slice dataset in 2d plane");
Same here

2023-02-09 03:33 UTC, bangerth commented
Oh, doh -- it hadn't occurred to me that there could be places where that appears in the names of parameters. I reverted the two places, thanks for pointing it out!

2023-02-09 14:32 UTC, tjhei commented
> , thanks for pointing it out

The testers did. :-)

2023-02-09 14:33 UTC, tjhei approved these changes

2023-02-10 13:32 UTC, merged