remove the condition DEAL_II_VERSION_GTE
geodynamics/aspect pull request #5198
Opened 2023-07-07 19:32 UTC by chameerasilva

2023-07-07 19:36 UTC, bangerth requested changes

2023-07-07 19:36 UTC, bangerth commented on source/particle/world.cc
> -#endif
This isn't right. The idea for the change is that ASPECT now requires deal.II 9.4 or later, and so the `#else` branch can't happen any more. But you need to keep the `#if` branch, along with all of the code you removed from below.

2023-07-07 19:36 UTC, bangerth commented on source/particle/world.cc
> -      });
Same here and for the other changes.

2023-07-07 21:31 UTC, bangerth requested changes

2023-07-07 21:31 UTC, bangerth commented on source/particle/world.cc
>  #endif
If you remove the `#if` and the `#else`, then you also need to remove the `#endif`.

Same below in all of the other parts of your patch.

2023-07-07 21:32 UTC, bangerth commented on source/particle/world.cc
>          this->get_triangulation().signals.weight.connect(
Separately, remove the empty line you have here. It looks odd if to have
```
if (particle_load_balancing & ParticleLoadBalancing::repartition)

  this->get_triangulation().signals.weight.connect(
```
with an empty line in the middle.

2023-07-08 17:47 UTC, bangerth requested changes
With the exception of the one comment, this is now conceptually correct.

But if you look at https://github.com/geodynamics/aspect/pull/5198/files , there are now a lot of empty lines in more or less random places where you removed the `#if` and `#endif` lines. It might be nice to clean that up a little bit to keep the code readable.

The empty lines are probably most easily visible on the right side of this page: https://github.com/geodynamics/aspect/pull/5198/files?diff=split&w=0 where you have all of these empty green lines.

2023-07-08 17:47 UTC, bangerth commented on source/particle/world.cc
> +!DEAL_II_VERSION_GTE(9,4,0)
You accidentally removed the `#if` here but left the condition in place. But this is not right in any case. The condition here is "if the deal.II version is NOT >=9.4", i.e., if the deal.II version is older than the minimum supported version. You can remove the whole block between `#if` and `#endif`.

2023-07-08 22:25 UTC, gassmoeller commented
/rebuild

2023-07-08 22:27 UTC, gassmoeller commented
There are still a number of new empty lines like Wolfgang mentioned above. Can you give it one more go to remove new empty lines that you added? You can use this link to find them (the green lines on the right hand side): https://github.com/geodynamics/aspect/pull/5198/files?diff=split&w=0

2023-07-08 22:46 UTC, gassmoeller commented
Thanks, this is ready to merge now. Let's wait for the testers.

2023-07-09 00:13 UTC, gassmoeller approved these changes

2023-07-09 00:14 UTC, gassmoeller commented
Congratulations to your first merged pull request to ASPECT :tada:

2023-07-09 00:20 UTC, bangerth approved these changes

2023-07-09 00:21 UTC, merged

2023-07-09 00:21 UTC, bangerth commented
Yay, nice! Thanks for going around on this a couple of times with me!