improved parameter description for replace_placeholders function
geodynamics/aspect pull request #5201
Opened 2023-07-07 21:30 UTC by mfmweerdesteijn

It wasn't clear that you cannot only specify the time step placeholder, even when there is only one boundary used. Very clear overview in the short Issue #4999 . I improved the replace_placeholders function description.

2023-07-07 22:12 UTC, bangerth requested changes

2023-07-07 22:12 UTC, bangerth commented on source/structured_data.cc
> +       */
You're currently talking to @MFraters about indentation. This is a place that the indentation script would have automatically fixed for you:
```suggestion
       */
```

2023-07-08 00:13 UTC, gassmoeller approved these changes

2023-07-08 00:13 UTC, gassmoeller commented
/rebuild

2023-07-08 04:36 UTC, bangerth approved these changes

2023-07-08 04:36 UTC, merged