Apply strict cutoff to the Peierls stress
geodynamics/aspect pull request #5229
Opened 2023-07-09 04:14 UTC by lhy11009

Pull Request Checklist. Please read and check each box with an X. Delete any part not applicable. Ask on the [forum](https://community.geodynamics.org/c/aspect) if you need help with any step.

In the Pull request, I add an option to use the "Cutoff stresses for Peierls creep" as strict cutoffs for the stress in the Peierls rheology. Previously, these values are used to ensure a gradual decreases of the Peierls strain rate towards 0 when the stress approaches 0. However, the values of the calculated Peierls creep viscosity could still be ultra small with the Idrissi 16 rheology at mantle conditions (T = 1673 K, strain rate = ${10}^{-15} s^{-1}$.  By adding this new option, the stress in the Peierls rheology cannot drop pass the cutoff stress anymore, thus reasonalely large values of Peierls viscosity could be achieved by adjusting the cutoff stress.

New test:

1. visco_plastic_peierls_strict_cutoff_test
The viscosity is computed at mantle condition from the Idrissi 16 rheology.  A strict cutoff is applied to rise the viscosity to a value of $5 \times {10}^{17} Pa s$ to demonstrate the usage of this option.

### Before your first pull request:

* [x] I have read the guidelines in our [CONTRIBUTING.md](../blob/main/CONTRIBUTING.md) document.

### For all pull requests:

* [x] I have followed the [instructions for indenting my code](../blob/main/CONTRIBUTING.md#making-aspect-better).

### For new features/models or changes of existing features:

* [x] I have tested my new feature locally to ensure it is correct.
* [x] I have [created a testcase](https://aspect-documentation.readthedocs.io/en/latest/user/extending/testing/writing-tests.html) for the new feature/benchmark in the [tests/](../blob/main/tests/) directory.
* [x] I have added a changelog entry in the [doc/modules/changes](../blob/main/doc/modules/changes) directory that will inform other users of my change.

2023-07-09 04:14 UTC, lhy11009 commented
@bobmyhill , second PR ready for review.

2023-07-09 05:27 UTC, bobmyhill requested changes
Very nice again. Just a couple of tweaks to the text required.
You'll also need to use unique names for the changelog files (we normally use `date_username_[b-z]`).

2023-07-09 05:27 UTC, bobmyhill commented on source/material_model/rheology/peierls_creep.cc
> +                           "Whether the Cutoff stresses for Peierls creep are applied strictly as the lower limits of "
```suggestion
                           "Whether the cutoff stresses for Peierls creep are used as the minimum "
```

2023-07-09 05:27 UTC, bobmyhill commented on source/material_model/rheology/peierls_creep.cc
> +                           "the stresses in the Peierls rheology");
```suggestion
                           "stresses in the Peierls rheology");
```

2023-07-09 05:27 UTC, bobmyhill commented on tests/visco_plastic_peierls_strict_cutoff_test.prm
> +# from the Peierls rheolgoy is cutoff below a cutoff stress
```suggestion
# from the Peierls rheology is limited by the cutoff stress
```

2023-07-09 15:22 UTC, gassmoeller commented
/rebuild

2023-07-09 18:34 UTC, lhy11009 commented
@bobmyhill , thanks for the review. Some updates:

1. Address the text comments.
2. Change name of changes log to 20230708_lhy11009

2023-07-10 05:20 UTC, bobmyhill approved these changes

2023-07-10 05:20 UTC, merged