[WIP] Use chemical compositions in rheology models for parameter parsing
geodynamics/aspect pull request #5542
Opened 2024-01-18 16:17 UTC by anne-glerum

For all the rheology models that the visco_plastic material model depends on, this PR uses the MapParsing functionality to retrieve material properties from the input file. This way, the parameter file does not have to specify properties for fields that to not represent chemical compositions (e.g., plastic strain). This saves entering a lot of values when stresses and/or strains are tracked, whose field type is automatically deduced from their field name set in the input file.

Let's see what the tester says first.

TODO update the declare_parameter descriptions to say that the list can be N+1 long where N is either the total nr of fields or the nr of chemical fields.

### For all pull requests:

* [x] I have followed the [instructions for indenting my code](../blob/main/CONTRIBUTING.md#making-aspect-better).

### For new features/models or changes of existing features:

* [ ] I have tested my new feature locally to ensure it is correct.
* [ ] I have [created a testcase](https://aspect-documentation.readthedocs.io/en/latest/user/extending/testing/writing-tests.html) for the new feature/benchmark in the [tests/](../blob/main/tests/) directory.
* [ ] I have added a changelog entry in the [doc/modules/changes](../blob/main/doc/modules/changes) directory that will inform other users of my change.

2024-01-24 11:36 UTC, bobmyhill requested changes
Brilliant, thanks @anne-glerum! A couple of very minor comments, but as long as the tests pass, this is basically ready to go.

2024-01-24 11:38 UTC, bobmyhill commented
/rebuild

2024-01-24 12:52 UTC, anne-glerum commented on source/material_model/visco_plastic.cc
> -                rheology->calculate_isostrain_viscosities(in, i, volume_fractions_for_rheology, phase_function_values, phase_function.n_phase_transitions_for_each_composition());
outdated

2024-01-24 12:57 UTC, anne-glerum commented on source/material_model/rheology/friction_models.cc
> +        // TODO Make sure functions only have to be specified per chemical composition,
Looking into it more, I think it should be adapted in this PR. The index used to select the right function is based on looping over the size of the chemical composition only volume_fractions. It is passed on by rheology/visco_plastic to the compute_friction_angle function. That function has functions for _all_ compositions, so then the index would be wrong.

2024-01-24 13:36 UTC, bobmyhill commented on source/material_model/visco_plastic.cc
> -                rheology->calculate_isostrain_viscosities(in, i, volume_fractions_for_rheology, phase_function_values, phase_function.n_phase_transitions_for_each_composition());
Sorry, this wasn't very clear. I meant I think lines 182-184 can now be removed.

2024-01-24 13:42 UTC, bobmyhill commented on source/material_model/visco_plastic.cc
> -                rheology->calculate_isostrain_viscosities(in, i, volume_fractions_for_rheology, phase_function_values, phase_function.n_phase_transitions_for_each_composition());
Thanks :)

2024-01-24 15:52 UTC, bobmyhill commented on source/material_model/diffusion_dislocation.cc
> +                             "for a total of N+1 values, where N is the number of all or only all chemical compositional fields. "
```suggestion
                             "for a total of N+1 values, where N is the number of all compositional fields or only those corresponding to chemical compositions. "
```

2024-01-24 15:56 UTC, bobmyhill commented on source/material_model/diffusion_dislocation.cc
> +                             "for a total of N+1 values, where N is the number of all or only all chemical compositional fields. "
ditto here and in all the other files. Sorry! Hopefully you can just find and replace.

2024-01-25 15:36 UTC, anne-glerum commented
Thanks for the quick review @bobmyhill, I've addressed your comments and the testsers pass (except for gmg tests on dealii-master).

2024-01-25 15:38 UTC, bobmyhill approved these changes

2024-01-25 15:42 UTC, bobmyhill commented
Brilliant, thanks! This will make prms so much neater.
Is this ready to merge from your end? I'll give it one last check to double check all the rheology function calls, and will then wait for your ok to merge.

2024-01-25 21:57 UTC, bobmyhill commented on doc/modules/changes/20240122_glerum
> + Improved: For the visco_plastic and visco_elastic
```suggestion
 Improved: For the diffusion_dislocation, visco_plastic and visco_elastic
```

2024-01-26 16:05 UTC, anne-glerum commented
Yes, from my side this is ready, thank you.

2024-01-26 16:24 UTC, bobmyhill commented
Ok, grand! Last thing; would you mind squashing a few commits? Perhaps the 4 test-related results (32be39b--795e312) and then 6190a41--c96986d could be squashed together.

2024-01-30 13:40 UTC, merged