Publication catch-up
geodynamics/aspect pull request #5663
Opened 2024-05-29 22:48 UTC by ljhwang

Getting caught up on adding ASPECT publications.  

Adding 3 new ones!

2024-05-29 23:18 UTC, gassmoeller approved these changes

2024-05-29 23:19 UTC, gassmoeller requested changes
sorry, too quick with my earlier review, there are two problems with the first entry.

2024-05-29 23:19 UTC, gassmoeller commented on doc/manual/citing_aspect.bib
> +pages = {0-0},
The tester complains about this page field.

2024-05-29 23:19 UTC, gassmoeller commented on doc/manual/citing_aspect.bib
> +author = {Hao Dong and Zebin Cao and Lijun Liu and Yanchong Li and Sanzhong Li and Liming Dai and and Xinyu Li}
The tester complains about the `and and` before the last name

2024-05-29 23:20 UTC, bangerth approved these changes

2024-05-29 23:21 UTC, bangerth commented
You've got some errors:
```
[1253] Utils.pm:293> WARN - Range field 'pages' in entry 'RA449-donghao' is malformed, falling back to literal
[1260] Utils.pm:293> WARN - Name in key 'RA449-donghao' is empty (probably consecutive 'and'): skipping entry 'RA449-donghao'
[1288] Utils.pm:293> WARN - BibTeX subsystem: substring 7, warning: empty substring
[9488] Biber.pm:128> INFO - WARNINGS: 3
```

2024-05-29 23:54 UTC, ljhwang commented
Thank goodness the tester is smarter than me. Note to self to recheck citations when prereleased before publication.  

The change updates the entire block to the current citation information.

2024-05-30 01:08 UTC, bangerth approved these changes

2024-05-30 01:29 UTC, gassmoeller approved these changes

2024-05-30 01:29 UTC, merged