adding_documentation_to_DP_rheology
geodynamics/aspect pull request #5733
Opened 2024-06-02 17:57 UTC by cedrict

Pull Request Checklist. Please read and check each box with an X. Delete any part not applicable. Ask on the [forum](https://community.geodynamics.org/c/aspect) if you need help with any step.

*Describe what you did in this PR and why you did it.*

### Before your first pull request:

* [ x] I have read the guidelines in our [CONTRIBUTING.md](../blob/main/CONTRIBUTING.md) document.

### For all pull requests:

* [x ] I have followed the [instructions for indenting my code](../blob/main/CONTRIBUTING.md#making-aspect-better).

### For new features/models or changes of existing features:

* [ ] I have tested my new feature locally to ensure it is correct.
* [ ] I have [created a testcase](https://aspect-documentation.readthedocs.io/en/latest/user/extending/testing/writing-tests.html) for the new feature/benchmark in the [tests/](../blob/main/tests/) directory.
* [ ] I have added a changelog entry in the [doc/modules/changes](../blob/main/doc/modules/changes) directory that will inform other users of my change.

2024-06-03 04:36 UTC, naliboff requested changes
@cedrict - Thanks for adding this documentation! One minor spelling correction needed (I suggest squashing the commits), and then good to merge.

2024-06-03 04:36 UTC, naliboff commented on source/material_model/rheology/drucker_prager.cc
> +        // There are actually three different ways of chosing this parameter, which
```suggestion
        // There are actually three different ways of choosing this parameter, which
```

2024-06-04 17:06 UTC, cedrict commented
@naliboff done

2024-06-05 12:45 UTC, gassmoeller approved these changes
Just a small fix, otherwise this is good to go. @naliboff: do you agree?

2024-06-05 16:58 UTC, naliboff approved these changes

2024-06-05 16:58 UTC, merged