Move particle plugin declarations to relative path instead of absolulte path.
geodynamics/aspect pull request #5896
Opened 2024-06-13 17:26 UTC by MFraters

Related to #5877. A first step for allowing multiple particle fields, by making the particle plugin path relative instead of absolute.

2024-06-13 20:30 UTC, gassmoeller commented
Like discussed, I think it is not particularly beautiful, because the parameter parsing in the particle plugins now looks differently from all other plugins, but I think it is the only reasonable solution. Why do you only do this in the `parse_parameters` function and not in the `declare_parameters` function? I think they should at least look similar.

2024-06-13 20:37 UTC, MFraters commented
I am doing it in both. I may have missed something? I am currently trying to fix the tests, which may show where I missed something. I will let you know as soon as I have fixed the tests and it is ready to review.

2024-06-14 14:37 UTC, MFraters commented
This pull request is now ready for review. All testers passed, but I noticed some parts where not covered while debuging,so I also have added some new test :)

2024-06-14 16:53 UTC, gassmoeller requested changes
let me talk to you about an idea I had

2024-06-14 19:39 UTC, tjhei approved these changes

2024-06-14 19:40 UTC, tjhei reviewed
Looks good to go from my side. @gassmoeller ?

2024-06-15 19:34 UTC, gassmoeller reviewed
Yes, I think this is the best way. Can you check my one comment?

2024-06-15 19:34 UTC, gassmoeller commented on source/particle/property/interface.cc
> +        property_list.back()->declare_parameters (prm);
Why did this work before you added this line? Are the declare_parameters functions of the plugins called from somewhere else?

2024-06-15 19:55 UTC, MFraters commented
@gassmoeller I have addressed your comments

2024-06-15 23:53 UTC, gassmoeller approved these changes
Looks great now. Thanks for testing my suggestions, even if they dont work out! :+1:

2024-06-15 23:53 UTC, merged