Fix extra text block colons.
geodynamics/aspect pull request #6146
Opened 2024-11-12 05:27 UTC by alarshi

I came across a small typo in the documentation (see below), this PR fixes it :) 

main:
![Screenshot from 2024-11-11 21-12-11](https://github.com/user-attachments/assets/589dc868-e6d7-441b-80a8-95be0c45c672)

this branch:
![image](https://github.com/user-attachments/assets/0a520de3-c2fd-4cba-a3ea-afbe10b4cd51)

2024-11-12 08:28 UTC, gassmoeller requested changes
Thanks for the fix! Unfortunately like all of the parameter documentation these are files that are automatically generated from the source code, so any change in the .md files will be overwritten the next time we update them. Could you instead fix line 1262 in source/postprocess/visualization.cc which is the original source of these colons?

2024-11-12 15:15 UTC, alarshi commented
Ah, yes. I keep forgetting it. Thank you for the review! :) 
I also realized that the issue was the incorrect rendering of the warning block above in `Filter output`. I fixed it in the last commit and the output should look like the image below:

![image](https://github.com/user-attachments/assets/cee0507f-267e-4f3a-99eb-3d98bf72bcbf)

2024-11-13 12:41 UTC, gassmoeller commented
/rebuild

2024-11-13 13:15 UTC, tjhei approved these changes
This is the only occurrence in the documentation of this problem. :+1:

2024-11-13 13:15 UTC, merged